// Generated by CoffeeScript 1.3.3
(function() {
  var init, resizeBorder, switchBorder;

  $(function() {
    return init();
  });

  init = function() {
    setTimeout(switchBorder, 3000);
    return resizeBorder();
  };

  switchBorder = function() {
    var as, body, newcolor;
    body = $('body');
    as = $('a');
    newcolor = Colors.rand();
    body.css('border-color', newcolor);
    return as.css('color', newcolor);
  };

  resizeBorder = function() {
    var body;
    body = $('body');
    body.css('min-height', window.innerHeight - 160 + 'px');
    return $(window).resize(function() {
      return body.css('min-height', window.innerHeight - 160 + 'px');
    });
  };

}).call(this);
