// Generated by CoffeeScript 1.3.3
(function() {
  var delay, init, resizeBorder, root, switchBorder;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Shade = {
    random: function(time) {
      if (time == null) {
        time = 2000;
      }
      return setTimeout((function() {
        return $('.shade').each(function() {
          $(this).css('color', Colors.rand());
          return Shade.random(time);
        });
      }), time);
    }
  };

  $(function() {
    return init();
  });

  init = function() {
    resizeBorder();
    if ($('body').hasClass('home')) {
      return setInterval(switchBorder, 5000);
    }
  };

  switchBorder = function() {
    var as, body, newcolor;
    body = $('body');
    as = $('a');
    newcolor = Colors.rand();
    body.css('border-color', newcolor);
    return as.css('color', newcolor);
  };

  resizeBorder = function() {
    var body, height;
    body = $('body');
    height = window.innerHeight - 160 + 'px';
    body.css('min-height', height);
    return $(window).resize(function() {
      return body.css('min-height', height);
    });
  };

  delay = function(ms, func) {
    return setTimeout(func, ms);
  };

}).call(this);
