// Generated by CoffeeScript 1.6.1
(function() {
  var delay, init, resizeBorder, switchBorder;

  $(function() {
    return init();
  });

  init = function() {
    resizeBorder();
    return $(window).resize(resizeBorder);
  };

  switchBorder = function() {
    var as, body, newcolor;
    body = $('body');
    as = $('a');
    newcolor = Colors.rand();
    body.css('border-color', newcolor);
    return as.css('color', newcolor);
  };

  resizeBorder = function() {
    var body, height;
    body = $('body');
    height = window.innerHeight - parseInt(body.css('padding')) * 2;
    body.css('min-height', height);
    return $(window).resize(function() {
      return body.css('min-height', height);
    });
  };

  delay = function(ms, func) {
    return setTimeout(func, ms);
  };

}).call(this);
