// Generated by CoffeeScript 1.3.3
(function() {
  var api_url, parse;

  _.templateSettings.interpolate = /\{\{(.+?)\}\}/g;

  api_url = 'http://joshellington.tumblr.com/api/read/json';

  $(function() {
    return parse(api_url, $('#main'));
  });

  parse = function(url, cont) {
    return $.ajax({
      url: url,
      dataType: 'jsonp',
      data: {
        api_key: 'ALTYK1FcaIeXBJ0T9Ro5nHdYeGA7rHhJtQg39ZCkLtNzwlNJfp'
      },
      success: function(d) {
        return _.each(d.posts, function(item, i) {
          var template;
          template = _.template($('script#blog-entry').html());
          log(item);
          item = {
            title: item['regular-title'],
            url: item['url'],
            date: Date.create(item['date-gmt']).short(),
            content: item['regular-body'],
            id: item['id']
          };
          return cont.html(template(item));
        });
      }
    });
  };

}).call(this);
